### ISSUE TITLE
Provide more meaningful error messages

### ISSUE THREAD

**Issue by glifchits** [glifchits/node-mvt-encoder#6]
Trying to integrate this module into an app I get:

```
  Error: Unsupported geometry type
      at features.forEach (/app/node_modules/mvt-encoder/tileEncoder.js:139:32)
      at Array.forEach (<anonymous>)
      at encodeFeatures (/app/node_modules/mvt-encoder/tileEncoder.js:138:12)
```
(provided EWKT from PostGIS, not a WKT)

or

```
  TypeError: Cannot read property 'count' of undefined
      at encodeGeometry (/app/node_modules/mvt-encoder/tileEncoder.js:74:45)
      at features.forEach (/app/node_modules/mvt-encoder/tileEncoder.js:144:17)
      at Array.forEach (<anonymous>)
```
(probably because I provided a `MULTIPOLYGON`)

Test cases to check:
- [ ] Unsupported input geometry (require WKT)
- [x] Unsupported geometry during encoding (only support POLYGON *for now*)
- [ ] Coordinates not scaled to tile extent (forgot to translate them)

**Comment by glifchits** [comment]
Test cases to check:
- [ ] Unsupported input geometry (require WKT)
- [ ] Unsupported geometry during encoding (only support POLYGON *for now*)
- [ ] Coordinates not scaled to tile extent (forgot to translate them)
